version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.9

      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo
    steps:
      - checkout

      - run: mix local.hex --force
      - run: mix local.rebar --force

      - run: mix deps.get
      - run: mix test
